"""empty message

Revision ID: 3e257546464e
Revises: 
Create Date: 2018-08-22 11:11:25.678655

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3e257546464e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('local_authority',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planning_application',
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('local_authority_id', sa.String(length=64), nullable=False),
    sa.Column('section106_signed_date', sa.Date(), nullable=True),
    sa.Column('section106_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['local_authority_id'], ['local_authority.id'], ),
    sa.PrimaryKeyConstraint('reference', 'local_authority_id')
    )
    op.create_table('contribution',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('contribution_type', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('obligation', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('planning_application', sa.String(length=64), nullable=False),
    sa.Column('local_authority_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['planning_application', 'local_authority_id'], ['planning_application.reference', 'planning_application.local_authority_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contribution')
    op.drop_table('planning_application')
    op.drop_table('local_authority')
    # ### end Alembic commands ###
