"""empty message

Revision ID: 5592419a8b23
Revises: 
Create Date: 2018-08-21 15:21:52.753993

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5592419a8b23'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('local_authority',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('section106_agreement',
    sa.Column('local_authority_id', sa.String(length=64), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('signed_date', sa.Date(), nullable=True),
    sa.Column('planning_application_reference', sa.String(length=64), nullable=True),
    sa.Column('planning_application_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['local_authority_id'], ['local_authority.id'], ),
    sa.PrimaryKeyConstraint('local_authority_id', 'reference')
    )
    op.create_table('contribution',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('contribution_type', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('obligation', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('section106_reference', sa.String(length=64), nullable=False),
    sa.Column('local_authority_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['section106_reference', 'local_authority_id'], ['section106_agreement.reference', 'section106_agreement.local_authority_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contribution')
    op.drop_table('section106_agreement')
    op.drop_table('local_authority')
    # ### end Alembic commands ###
