"""empty message

Revision ID: 73bfbb7ede22
Revises: 
Create Date: 2018-08-21 13:42:21.469937

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '73bfbb7ede22'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('local_authority',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planning_application',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('local_authority_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['local_authority_id'], ['local_authority.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('section106',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('agreement_date', sa.Date(), nullable=True),
    sa.Column('planning_application_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['planning_application_id'], ['planning_application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contribution',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('contribution_type', sa.String(), nullable=True),
    sa.Column('section106_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['section106_id'], ['section106.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contribution')
    op.drop_table('section106')
    op.drop_table('planning_application')
    op.drop_table('local_authority')
    # ### end Alembic commands ###
