"""empty message

Revision ID: 8d1a35a4e8a1
Revises: dc5e86527666
Create Date: 2018-12-10 11:23:35.865647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d1a35a4e8a1'
down_revision = 'dc5e86527666'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viability_assessment', sa.Column('total_cost', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('viability_assessment', 'total_cost')
    # ### end Alembic commands ###
