"""empty message

Revision ID: 963bd289b895
Revises: b44d803f00ae
Create Date: 2018-09-04 17:19:02.274273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '963bd289b895'
down_revision = 'b44d803f00ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('viability_assessment', column_name='planning_application', new_column_name='planning_application_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('viability_assessment', column_name='planning_application_id', new_column_name='planning_application')
    # ### end Alembic commands ###
