"""empty message

Revision ID: b44d803f00ae
Revises: 3e257546464e
Create Date: 2018-09-04 11:48:17.812994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b44d803f00ae'
down_revision = '3e257546464e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('viability_assessment',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('planning_application', sa.String(length=64), nullable=False),
    sa.Column('local_authority_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['planning_application', 'local_authority_id'], ['planning_application.reference', 'planning_application.local_authority_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('viability_assessment')
    # ### end Alembic commands ###
