"""empty message

Revision ID: dc5e86527666
Revises: 986668bdd192
Create Date: 2018-09-05 15:09:59.653866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc5e86527666'
down_revision = '986668bdd192'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viability_assessment', sa.Column('benchmark_land_value', sa.Integer(), nullable=True))
    op.add_column('viability_assessment', sa.Column('gross_development_value', sa.Integer(), nullable=True))
    op.add_column('viability_assessment', sa.Column('total_contribution', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('viability_assessment', 'total_contribution')
    op.drop_column('viability_assessment', 'gross_development_value')
    op.drop_column('viability_assessment', 'benchmark_land_value')
    # ### end Alembic commands ###
